### ISSUE TITLE
The program could not be started

### ISSUE THREAD

**Issue by lyonnee** [subspace/space-acres#171]
```
024-03-27T06:23:48.808868Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813348 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 46.2kiB/s ⬆ 0.7kiB/s    
2024-03-27T06:23:53.809134Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813349 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 44.3kiB/s ⬆ 0.8kiB/s    
2024-03-27T06:23:58.809360Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813350 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 37.4kiB/s ⬆ 1.0kiB/s    
2024-03-27T06:24:03.809617Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813350 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 31.4kiB/s ⬆ 0.9kiB/s    
2024-03-27T06:24:08.809841Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813352 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 46.8kiB/s ⬆ 0.9kiB/s    
2024-03-27T06:24:13.810088Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813352 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 36.4kiB/s ⬆ 0.8kiB/s    
2024-03-27T06:24:18.810296Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813353 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 38.4kiB/s ⬆ 0.7kiB/s    
2024-03-27T06:24:23.810489Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813353 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 23.6kiB/s ⬆ 0.9kiB/s    
2024-03-27T06:24:28.810686Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813355 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 32.4kiB/s ⬆ 0.7kiB/s    
2024-03-27T06:24:33.810876Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813355 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 33.0kiB/s ⬆ 0.7kiB/s    
2024-03-27T06:24:38.811132Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813355 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 29.6kiB/s ⬆ 0.7kiB/s    
2024-03-27T06:24:43.811905Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813355 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 30.6kiB/s ⬆ 0.7kiB/s    
2024-03-27T06:24:48.812398Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813355 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 18.3kiB/s ⬆ 0.4kiB/s    
2024-03-27T06:24:53.812665Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813356 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 35.1kiB/s ⬆ 0.7kiB/s    
2024-03-27T06:24:58.812921Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813358 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 35.9kiB/s ⬆ 1.0kiB/s    
2024-03-27T06:25:03.813166Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813359 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 48.8kiB/s ⬆ 1.3kiB/s    
2024-03-27T06:25:08.813362Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813361 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 51.2kiB/s ⬆ 1.2kiB/s    
2024-03-27T06:25:13.813673Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813363 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 25.7kiB/s ⬆ 1.0kiB/s    
2024-03-27T06:25:18.813910Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813365 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 27.3kiB/s ⬆ 0.6kiB/s    
2024-03-27T06:25:23.814107Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813365 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 36.5kiB/s ⬆ 0.6kiB/s    
2024-03-27T06:25:28.814310Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813366 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 39.1kiB/s ⬆ 0.5kiB/s    
2024-03-27T06:25:33.814658Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813368 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 29.6kiB/s ⬆ 0.9kiB/s    
2024-03-27T06:25:38.814846Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813368 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 33.1kiB/s ⬆ 0.6kiB/s    
2024-03-27T06:25:43.815054Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813368 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 40.7kiB/s ⬆ 0.6kiB/s    
2024-03-27T06:25:48.815426Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813368 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 38.6kiB/s ⬆ 0.5kiB/s    
2024-03-27T06:25:53.815667Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813368 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 40.7kiB/s ⬆ 0.6kiB/s    
2024-03-27T06:25:58.815934Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813369 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 28.9kiB/s ⬆ 0.7kiB/s    
2024-03-27T06:26:03.816151Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813371 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 46.8kiB/s ⬆ 1.3kiB/s    
2024-03-27T06:26:08.816368Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813371 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 32.6kiB/s ⬆ 0.8kiB/s    
2024-03-27T06:26:13.816545Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813371 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 26.5kiB/s ⬆ 1.1kiB/s    
2024-03-27T06:26:18.816759Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813371 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 37.7kiB/s ⬆ 1.2kiB/s    
2024-03-27T06:26:23.816994Z  INFO Node: substrate: ⚙️  Syncing  0.0 bps, target=#813371 (37 peers), best: #452227 (0x3489…b8d9), finalized #451881 (0x5c84…b4e7), ⬇ 26.4kiB/s ⬆ 1.5kiB/s    
2024-03-27T07:42:57.293206Z  INFO space_acres: Starting space-acres 0.1.11
2024-03-27T07:42:58.408316Z  INFO Network: subspace_networking::constructor: DSN instance configured. allow_non_global_addresses_in_dht=false peer_id=12D3KooWSKDdVjUtJ9FZ9rLqXFgunN9dKaGvimjwoYByxyeZuUoQ protocol_version=/subspace/2/0c121c75f4ef450f40619e1fca9d1e8e7fbabc42c895bc4790801e85d5a91c34
2024-03-27T07:42:58.449576Z  INFO Network: libp2p_swarm: local_peer_id=12D3KooWSKDdVjUtJ9FZ9rLqXFgunN9dKaGvimjwoYByxyeZuUoQ
2024-03-27T07:45:08.862358Z  INFO Node: block_relay: relay::consensus block server: starting
2024-03-27T07:45:08.867389Z  INFO Node: sub-libp2p: 🏷  Local node identity is: 12D3KooWSKDdVjUtJ9FZ9rLqXFgunN9dKaGvimjwoYByxyeZuUoQ    
thread 'backend' panicked at /home/runner/.cargo/git/checkouts/subspace-5c1447fb849a5554/b970b6a/crates/sc-consensus-subspace/src/archiver.rs:300:14:
Last archived block must always be retrievable; qed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-03-27T07:45:08.884976Z  WARN Node: sc_service::builder: The NetworkStart returned as part of `build_network` has been silently dropped    
thread 'main' panicked at /home/runner/.cargo/git/checkouts/subspace-5c1447fb849a5554/b970b6a/crates/subspace-farmer/src/utils.rs:82:14:
Panic if background thread panicked: Any { .. }
2024-03-27T09:25:29.721336Z  INFO space_acres: Exiting space-acres 0.1.11 exit_status_code=Exit
2024-03-27T09:39:45.991749Z  INFO space_acres: Starting space-acres 0.1.11
2024-03-27T09:39:48.568779Z  WARN space_acres::frontend::new_version: Failed to check new release error=error sending request for url (https://api.github.com/repos/subspace/space-acres/releases/latest): error trying to connect: dns error: failed to lookup address information: 名称或服务未知 url=https://api.github.com/repos/subspace/space-acres/releases/latest
2024-03-27T09:39:48.690372Z  INFO Network: subspace_networking::constructor: DSN instance configured. allow_non_global_addresses_in_dht=false peer_id=12D3KooWSKDdVjUtJ9FZ9rLqXFgunN9dKaGvimjwoYByxyeZuUoQ protocol_version=/subspace/2/0c121c75f4ef450f40619e1fca9d1e8e7fbabc42c895bc4790801e85d5a91c34
2024-03-27T09:39:48.818301Z  INFO Network: libp2p_swarm: local_peer_id=12D3KooWSKDdVjUtJ9FZ9rLqXFgunN9dKaGvimjwoYByxyeZuUoQ
2024-03-27T09:39:57.952107Z  INFO Node: block_relay: relay::consensus block server: starting
2024-03-27T09:39:57.968489Z  INFO Node: sub-libp2p: 🏷  Local node identity is: 12D3KooWSKDdVjUtJ9FZ9rLqXFgunN9dKaGvimjwoYByxyeZuUoQ    
thread 'backend' panicked at /home/runner/.cargo/git/checkouts/subspace-5c1447fb849a5554/b970b6a/crates/sc-consensus-subspace/src/archiver.rs:300:14:
Last archived block must always be retrievable; qed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-03-27T09:39:58.051796Z  WARN Node: sc_service::builder: The NetworkStart returned as part of `build_network` has been silently dropped    
thread 'main' panicked at /home/runner/.cargo/git/checkouts/subspace-5c1447fb849a5554/b970b6a/crates/subspace-farmer/src/utils.rs:82:14:
Panic if background thread panicked: Any { .. }
```

**Comment by nazar-pc** [comment]
This should never happen as the error says, can you provide a bit of background how you got into this situation?

**Comment by lyonnee** [comment]
The program quits unexpectedly, and it can't be started again

**Comment by nazar-pc** [comment]
I can see that, but what did you do before that? Like did you upgrade from CLI for example?

**Comment by lyonnee** [comment]
> I can see that, but what did you do before that? Like did you upgrade from CLI for example?

no, the program ran silently in the background until I found it crashed

**Comment by nazar-pc** [comment]
Looks like your node quite far out of sync already, I suggest you remove `db` from node directory and it it sync from scratch again. You will not loose plotted sectors in the process.

**Comment by lyonnee** [comment]
> Looks like your node quite far out of sync already, I suggest you remove `db` from node directory and it it sync from scratch again. You will not loose plotted sectors in the process.

ok, the client has boot

**Comment by nazar-pc** [comment]
Closing for now then
